services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: orbit-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Passw0rd"
    ports:
      - "14330:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  redis:
    image: redis:7-alpine
    container_name: orbit-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: orbit-redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight-data:/data
    depends_on:
      - redis

volumes:
  sqlserver-data:
  redis-data:
  redisinsight-data:
